/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WireframesSettingsRouteImport } from './routes/wireframes/settings'
import { Route as WireframesSearchRouteImport } from './routes/wireframes/search'
import { Route as WireframesProfileManagementRouteImport } from './routes/wireframes/profile-management'
import { Route as WireframesProfileRouteImport } from './routes/wireframes/profile'
import { Route as WireframesProductRouteImport } from './routes/wireframes/product'
import { Route as WireframesLandingRouteImport } from './routes/wireframes/landing'
import { Route as WireframesCommunicationCenterRouteImport } from './routes/wireframes/communication-center'
import { Route as WireframesSystemSupportTicketsRouteImport } from './routes/wireframes/system/support-tickets'
import { Route as WireframesSystemNotificationCenterRouteImport } from './routes/wireframes/system/notification-center'
import { Route as WireframesSystemEmailTemplatesRouteImport } from './routes/wireframes/system/email-templates'
import { Route as WireframesSystemDeliveryDownloadRouteImport } from './routes/wireframes/system/delivery-download'
import { Route as WireframesSellerProductManagementRouteImport } from './routes/wireframes/seller/product-management'
import { Route as WireframesSellerOfferManagementRouteImport } from './routes/wireframes/seller/offer-management'
import { Route as WireframesSellerOfferAnalyticsRouteImport } from './routes/wireframes/seller/offer-analytics'
import { Route as WireframesSellerOfferRouteImport } from './routes/wireframes/seller/offer'
import { Route as WireframesSellerDashboardRouteImport } from './routes/wireframes/seller/dashboard'
import { Route as WireframesSellerContractManagementRouteImport } from './routes/wireframes/seller/contract-management'
import { Route as WireframesSellerAddProductRouteImport } from './routes/wireframes/seller/add-product'
import { Route as WireframesModeratorDashboardRouteImport } from './routes/wireframes/moderator/dashboard'
import { Route as WireframesLegalDocumentCenterRouteImport } from './routes/wireframes/legal/document-center'
import { Route as WireframesLegalDisputeResolutionRouteImport } from './routes/wireframes/legal/dispute-resolution'
import { Route as WireframesLegalContractTemplatesRouteImport } from './routes/wireframes/legal/contract-templates'
import { Route as WireframesContractManagerDashboardRouteImport } from './routes/wireframes/contract-manager/dashboard'
import { Route as WireframesContractManagerCreateContractRouteImport } from './routes/wireframes/contract-manager/create-contract'
import { Route as WireframesBuyerPaymentRouteImport } from './routes/wireframes/buyer/payment'
import { Route as WireframesBuyerOfferTrackingRouteImport } from './routes/wireframes/buyer/offer-tracking'
import { Route as WireframesBuyerOfferReviewSignRouteImport } from './routes/wireframes/buyer/offer-review-sign'
import { Route as WireframesBuyerLibraryRouteImport } from './routes/wireframes/buyer/library'
import { Route as WireframesBuyerDashboardRouteImport } from './routes/wireframes/buyer/dashboard'
import { Route as WireframesBuyerCreateOfferRouteImport } from './routes/wireframes/buyer/create-offer'
import { Route as WireframesBuyerContractManagementRouteImport } from './routes/wireframes/buyer/contract-management'
import { Route as WireframesAuthenticationSignupRouteImport } from './routes/wireframes/authentication/signup'
import { Route as WireframesAuthenticationResetPasswordRouteImport } from './routes/wireframes/authentication/reset-password'
import { Route as WireframesAuthenticationLoginRouteImport } from './routes/wireframes/authentication/login'
import { Route as WireframesAuthenticationKycRouteImport } from './routes/wireframes/authentication/kyc'
import { Route as WireframesAuthenticationForgotPasswordRouteImport } from './routes/wireframes/authentication/forgot-password'
import { Route as WireframesAuthenticationEmailVerificationRouteImport } from './routes/wireframes/authentication/email-verification'
import { Route as WireframesAdminUserManagementRouteImport } from './routes/wireframes/admin/user-management'
import { Route as WireframesAdminSystemMonitoringRouteImport } from './routes/wireframes/admin/system-monitoring'
import { Route as WireframesAdminRoleManagementRouteImport } from './routes/wireframes/admin/role-management'
import { Route as WireframesAdminOfferManagementRouteImport } from './routes/wireframes/admin/offer-management'
import { Route as WireframesAdminFinancialReportsRouteImport } from './routes/wireframes/admin/financial-reports'
import { Route as WireframesAdminDashboardRouteImport } from './routes/wireframes/admin/dashboard'
import { Route as WireframesAdminContractManagementRouteImport } from './routes/wireframes/admin/contract-management'
import { Route as WireframesAdminAnalyticsRouteImport } from './routes/wireframes/admin/analytics'
import { Route as WireframesAdminAdminProductModerationRouteImport } from './routes/wireframes/admin/admin-product-moderation'
import { Route as WireframesAdminAdminKycApprovalRouteImport } from './routes/wireframes/admin/admin-kyc-approval'
import { Route as WireframesAccountantPaymentVerifyRouteImport } from './routes/wireframes/accountant/payment-verify'
import { Route as WireframesAccountantDashboardRouteImport } from './routes/wireframes/accountant/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WireframesSettingsRoute = WireframesSettingsRouteImport.update({
  id: '/wireframes/settings',
  path: '/wireframes/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WireframesSearchRoute = WireframesSearchRouteImport.update({
  id: '/wireframes/search',
  path: '/wireframes/search',
  getParentRoute: () => rootRouteImport,
} as any)
const WireframesProfileManagementRoute =
  WireframesProfileManagementRouteImport.update({
    id: '/wireframes/profile-management',
    path: '/wireframes/profile-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesProfileRoute = WireframesProfileRouteImport.update({
  id: '/wireframes/profile',
  path: '/wireframes/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WireframesProductRoute = WireframesProductRouteImport.update({
  id: '/wireframes/product',
  path: '/wireframes/product',
  getParentRoute: () => rootRouteImport,
} as any)
const WireframesLandingRoute = WireframesLandingRouteImport.update({
  id: '/wireframes/landing',
  path: '/wireframes/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const WireframesCommunicationCenterRoute =
  WireframesCommunicationCenterRouteImport.update({
    id: '/wireframes/communication-center',
    path: '/wireframes/communication-center',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesSystemSupportTicketsRoute =
  WireframesSystemSupportTicketsRouteImport.update({
    id: '/wireframes/system/support-tickets',
    path: '/wireframes/system/support-tickets',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesSystemNotificationCenterRoute =
  WireframesSystemNotificationCenterRouteImport.update({
    id: '/wireframes/system/notification-center',
    path: '/wireframes/system/notification-center',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesSystemEmailTemplatesRoute =
  WireframesSystemEmailTemplatesRouteImport.update({
    id: '/wireframes/system/email-templates',
    path: '/wireframes/system/email-templates',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesSystemDeliveryDownloadRoute =
  WireframesSystemDeliveryDownloadRouteImport.update({
    id: '/wireframes/system/delivery-download',
    path: '/wireframes/system/delivery-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesSellerProductManagementRoute =
  WireframesSellerProductManagementRouteImport.update({
    id: '/wireframes/seller/product-management',
    path: '/wireframes/seller/product-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesSellerOfferManagementRoute =
  WireframesSellerOfferManagementRouteImport.update({
    id: '/wireframes/seller/offer-management',
    path: '/wireframes/seller/offer-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesSellerOfferAnalyticsRoute =
  WireframesSellerOfferAnalyticsRouteImport.update({
    id: '/wireframes/seller/offer-analytics',
    path: '/wireframes/seller/offer-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesSellerOfferRoute = WireframesSellerOfferRouteImport.update({
  id: '/wireframes/seller/offer',
  path: '/wireframes/seller/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const WireframesSellerDashboardRoute =
  WireframesSellerDashboardRouteImport.update({
    id: '/wireframes/seller/dashboard',
    path: '/wireframes/seller/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesSellerContractManagementRoute =
  WireframesSellerContractManagementRouteImport.update({
    id: '/wireframes/seller/contract-management',
    path: '/wireframes/seller/contract-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesSellerAddProductRoute =
  WireframesSellerAddProductRouteImport.update({
    id: '/wireframes/seller/add-product',
    path: '/wireframes/seller/add-product',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesModeratorDashboardRoute =
  WireframesModeratorDashboardRouteImport.update({
    id: '/wireframes/moderator/dashboard',
    path: '/wireframes/moderator/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesLegalDocumentCenterRoute =
  WireframesLegalDocumentCenterRouteImport.update({
    id: '/wireframes/legal/document-center',
    path: '/wireframes/legal/document-center',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesLegalDisputeResolutionRoute =
  WireframesLegalDisputeResolutionRouteImport.update({
    id: '/wireframes/legal/dispute-resolution',
    path: '/wireframes/legal/dispute-resolution',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesLegalContractTemplatesRoute =
  WireframesLegalContractTemplatesRouteImport.update({
    id: '/wireframes/legal/contract-templates',
    path: '/wireframes/legal/contract-templates',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesContractManagerDashboardRoute =
  WireframesContractManagerDashboardRouteImport.update({
    id: '/wireframes/contract-manager/dashboard',
    path: '/wireframes/contract-manager/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesContractManagerCreateContractRoute =
  WireframesContractManagerCreateContractRouteImport.update({
    id: '/wireframes/contract-manager/create-contract',
    path: '/wireframes/contract-manager/create-contract',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesBuyerPaymentRoute = WireframesBuyerPaymentRouteImport.update({
  id: '/wireframes/buyer/payment',
  path: '/wireframes/buyer/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const WireframesBuyerOfferTrackingRoute =
  WireframesBuyerOfferTrackingRouteImport.update({
    id: '/wireframes/buyer/offer-tracking',
    path: '/wireframes/buyer/offer-tracking',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesBuyerOfferReviewSignRoute =
  WireframesBuyerOfferReviewSignRouteImport.update({
    id: '/wireframes/buyer/offer-review-sign',
    path: '/wireframes/buyer/offer-review-sign',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesBuyerLibraryRoute = WireframesBuyerLibraryRouteImport.update({
  id: '/wireframes/buyer/library',
  path: '/wireframes/buyer/library',
  getParentRoute: () => rootRouteImport,
} as any)
const WireframesBuyerDashboardRoute =
  WireframesBuyerDashboardRouteImport.update({
    id: '/wireframes/buyer/dashboard',
    path: '/wireframes/buyer/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesBuyerCreateOfferRoute =
  WireframesBuyerCreateOfferRouteImport.update({
    id: '/wireframes/buyer/create-offer',
    path: '/wireframes/buyer/create-offer',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesBuyerContractManagementRoute =
  WireframesBuyerContractManagementRouteImport.update({
    id: '/wireframes/buyer/contract-management',
    path: '/wireframes/buyer/contract-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAuthenticationSignupRoute =
  WireframesAuthenticationSignupRouteImport.update({
    id: '/wireframes/authentication/signup',
    path: '/wireframes/authentication/signup',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAuthenticationResetPasswordRoute =
  WireframesAuthenticationResetPasswordRouteImport.update({
    id: '/wireframes/authentication/reset-password',
    path: '/wireframes/authentication/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAuthenticationLoginRoute =
  WireframesAuthenticationLoginRouteImport.update({
    id: '/wireframes/authentication/login',
    path: '/wireframes/authentication/login',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAuthenticationKycRoute =
  WireframesAuthenticationKycRouteImport.update({
    id: '/wireframes/authentication/kyc',
    path: '/wireframes/authentication/kyc',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAuthenticationForgotPasswordRoute =
  WireframesAuthenticationForgotPasswordRouteImport.update({
    id: '/wireframes/authentication/forgot-password',
    path: '/wireframes/authentication/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAuthenticationEmailVerificationRoute =
  WireframesAuthenticationEmailVerificationRouteImport.update({
    id: '/wireframes/authentication/email-verification',
    path: '/wireframes/authentication/email-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAdminUserManagementRoute =
  WireframesAdminUserManagementRouteImport.update({
    id: '/wireframes/admin/user-management',
    path: '/wireframes/admin/user-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAdminSystemMonitoringRoute =
  WireframesAdminSystemMonitoringRouteImport.update({
    id: '/wireframes/admin/system-monitoring',
    path: '/wireframes/admin/system-monitoring',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAdminRoleManagementRoute =
  WireframesAdminRoleManagementRouteImport.update({
    id: '/wireframes/admin/role-management',
    path: '/wireframes/admin/role-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAdminOfferManagementRoute =
  WireframesAdminOfferManagementRouteImport.update({
    id: '/wireframes/admin/offer-management',
    path: '/wireframes/admin/offer-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAdminFinancialReportsRoute =
  WireframesAdminFinancialReportsRouteImport.update({
    id: '/wireframes/admin/financial-reports',
    path: '/wireframes/admin/financial-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAdminDashboardRoute =
  WireframesAdminDashboardRouteImport.update({
    id: '/wireframes/admin/dashboard',
    path: '/wireframes/admin/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAdminContractManagementRoute =
  WireframesAdminContractManagementRouteImport.update({
    id: '/wireframes/admin/contract-management',
    path: '/wireframes/admin/contract-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAdminAnalyticsRoute =
  WireframesAdminAnalyticsRouteImport.update({
    id: '/wireframes/admin/analytics',
    path: '/wireframes/admin/analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAdminAdminProductModerationRoute =
  WireframesAdminAdminProductModerationRouteImport.update({
    id: '/wireframes/admin/admin-product-moderation',
    path: '/wireframes/admin/admin-product-moderation',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAdminAdminKycApprovalRoute =
  WireframesAdminAdminKycApprovalRouteImport.update({
    id: '/wireframes/admin/admin-kyc-approval',
    path: '/wireframes/admin/admin-kyc-approval',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAccountantPaymentVerifyRoute =
  WireframesAccountantPaymentVerifyRouteImport.update({
    id: '/wireframes/accountant/payment-verify',
    path: '/wireframes/accountant/payment-verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const WireframesAccountantDashboardRoute =
  WireframesAccountantDashboardRouteImport.update({
    id: '/wireframes/accountant/dashboard',
    path: '/wireframes/accountant/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wireframes/communication-center': typeof WireframesCommunicationCenterRoute
  '/wireframes/landing': typeof WireframesLandingRoute
  '/wireframes/product': typeof WireframesProductRoute
  '/wireframes/profile': typeof WireframesProfileRoute
  '/wireframes/profile-management': typeof WireframesProfileManagementRoute
  '/wireframes/search': typeof WireframesSearchRoute
  '/wireframes/settings': typeof WireframesSettingsRoute
  '/wireframes/accountant/dashboard': typeof WireframesAccountantDashboardRoute
  '/wireframes/accountant/payment-verify': typeof WireframesAccountantPaymentVerifyRoute
  '/wireframes/admin/admin-kyc-approval': typeof WireframesAdminAdminKycApprovalRoute
  '/wireframes/admin/admin-product-moderation': typeof WireframesAdminAdminProductModerationRoute
  '/wireframes/admin/analytics': typeof WireframesAdminAnalyticsRoute
  '/wireframes/admin/contract-management': typeof WireframesAdminContractManagementRoute
  '/wireframes/admin/dashboard': typeof WireframesAdminDashboardRoute
  '/wireframes/admin/financial-reports': typeof WireframesAdminFinancialReportsRoute
  '/wireframes/admin/offer-management': typeof WireframesAdminOfferManagementRoute
  '/wireframes/admin/role-management': typeof WireframesAdminRoleManagementRoute
  '/wireframes/admin/system-monitoring': typeof WireframesAdminSystemMonitoringRoute
  '/wireframes/admin/user-management': typeof WireframesAdminUserManagementRoute
  '/wireframes/authentication/email-verification': typeof WireframesAuthenticationEmailVerificationRoute
  '/wireframes/authentication/forgot-password': typeof WireframesAuthenticationForgotPasswordRoute
  '/wireframes/authentication/kyc': typeof WireframesAuthenticationKycRoute
  '/wireframes/authentication/login': typeof WireframesAuthenticationLoginRoute
  '/wireframes/authentication/reset-password': typeof WireframesAuthenticationResetPasswordRoute
  '/wireframes/authentication/signup': typeof WireframesAuthenticationSignupRoute
  '/wireframes/buyer/contract-management': typeof WireframesBuyerContractManagementRoute
  '/wireframes/buyer/create-offer': typeof WireframesBuyerCreateOfferRoute
  '/wireframes/buyer/dashboard': typeof WireframesBuyerDashboardRoute
  '/wireframes/buyer/library': typeof WireframesBuyerLibraryRoute
  '/wireframes/buyer/offer-review-sign': typeof WireframesBuyerOfferReviewSignRoute
  '/wireframes/buyer/offer-tracking': typeof WireframesBuyerOfferTrackingRoute
  '/wireframes/buyer/payment': typeof WireframesBuyerPaymentRoute
  '/wireframes/contract-manager/create-contract': typeof WireframesContractManagerCreateContractRoute
  '/wireframes/contract-manager/dashboard': typeof WireframesContractManagerDashboardRoute
  '/wireframes/legal/contract-templates': typeof WireframesLegalContractTemplatesRoute
  '/wireframes/legal/dispute-resolution': typeof WireframesLegalDisputeResolutionRoute
  '/wireframes/legal/document-center': typeof WireframesLegalDocumentCenterRoute
  '/wireframes/moderator/dashboard': typeof WireframesModeratorDashboardRoute
  '/wireframes/seller/add-product': typeof WireframesSellerAddProductRoute
  '/wireframes/seller/contract-management': typeof WireframesSellerContractManagementRoute
  '/wireframes/seller/dashboard': typeof WireframesSellerDashboardRoute
  '/wireframes/seller/offer': typeof WireframesSellerOfferRoute
  '/wireframes/seller/offer-analytics': typeof WireframesSellerOfferAnalyticsRoute
  '/wireframes/seller/offer-management': typeof WireframesSellerOfferManagementRoute
  '/wireframes/seller/product-management': typeof WireframesSellerProductManagementRoute
  '/wireframes/system/delivery-download': typeof WireframesSystemDeliveryDownloadRoute
  '/wireframes/system/email-templates': typeof WireframesSystemEmailTemplatesRoute
  '/wireframes/system/notification-center': typeof WireframesSystemNotificationCenterRoute
  '/wireframes/system/support-tickets': typeof WireframesSystemSupportTicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wireframes/communication-center': typeof WireframesCommunicationCenterRoute
  '/wireframes/landing': typeof WireframesLandingRoute
  '/wireframes/product': typeof WireframesProductRoute
  '/wireframes/profile': typeof WireframesProfileRoute
  '/wireframes/profile-management': typeof WireframesProfileManagementRoute
  '/wireframes/search': typeof WireframesSearchRoute
  '/wireframes/settings': typeof WireframesSettingsRoute
  '/wireframes/accountant/dashboard': typeof WireframesAccountantDashboardRoute
  '/wireframes/accountant/payment-verify': typeof WireframesAccountantPaymentVerifyRoute
  '/wireframes/admin/admin-kyc-approval': typeof WireframesAdminAdminKycApprovalRoute
  '/wireframes/admin/admin-product-moderation': typeof WireframesAdminAdminProductModerationRoute
  '/wireframes/admin/analytics': typeof WireframesAdminAnalyticsRoute
  '/wireframes/admin/contract-management': typeof WireframesAdminContractManagementRoute
  '/wireframes/admin/dashboard': typeof WireframesAdminDashboardRoute
  '/wireframes/admin/financial-reports': typeof WireframesAdminFinancialReportsRoute
  '/wireframes/admin/offer-management': typeof WireframesAdminOfferManagementRoute
  '/wireframes/admin/role-management': typeof WireframesAdminRoleManagementRoute
  '/wireframes/admin/system-monitoring': typeof WireframesAdminSystemMonitoringRoute
  '/wireframes/admin/user-management': typeof WireframesAdminUserManagementRoute
  '/wireframes/authentication/email-verification': typeof WireframesAuthenticationEmailVerificationRoute
  '/wireframes/authentication/forgot-password': typeof WireframesAuthenticationForgotPasswordRoute
  '/wireframes/authentication/kyc': typeof WireframesAuthenticationKycRoute
  '/wireframes/authentication/login': typeof WireframesAuthenticationLoginRoute
  '/wireframes/authentication/reset-password': typeof WireframesAuthenticationResetPasswordRoute
  '/wireframes/authentication/signup': typeof WireframesAuthenticationSignupRoute
  '/wireframes/buyer/contract-management': typeof WireframesBuyerContractManagementRoute
  '/wireframes/buyer/create-offer': typeof WireframesBuyerCreateOfferRoute
  '/wireframes/buyer/dashboard': typeof WireframesBuyerDashboardRoute
  '/wireframes/buyer/library': typeof WireframesBuyerLibraryRoute
  '/wireframes/buyer/offer-review-sign': typeof WireframesBuyerOfferReviewSignRoute
  '/wireframes/buyer/offer-tracking': typeof WireframesBuyerOfferTrackingRoute
  '/wireframes/buyer/payment': typeof WireframesBuyerPaymentRoute
  '/wireframes/contract-manager/create-contract': typeof WireframesContractManagerCreateContractRoute
  '/wireframes/contract-manager/dashboard': typeof WireframesContractManagerDashboardRoute
  '/wireframes/legal/contract-templates': typeof WireframesLegalContractTemplatesRoute
  '/wireframes/legal/dispute-resolution': typeof WireframesLegalDisputeResolutionRoute
  '/wireframes/legal/document-center': typeof WireframesLegalDocumentCenterRoute
  '/wireframes/moderator/dashboard': typeof WireframesModeratorDashboardRoute
  '/wireframes/seller/add-product': typeof WireframesSellerAddProductRoute
  '/wireframes/seller/contract-management': typeof WireframesSellerContractManagementRoute
  '/wireframes/seller/dashboard': typeof WireframesSellerDashboardRoute
  '/wireframes/seller/offer': typeof WireframesSellerOfferRoute
  '/wireframes/seller/offer-analytics': typeof WireframesSellerOfferAnalyticsRoute
  '/wireframes/seller/offer-management': typeof WireframesSellerOfferManagementRoute
  '/wireframes/seller/product-management': typeof WireframesSellerProductManagementRoute
  '/wireframes/system/delivery-download': typeof WireframesSystemDeliveryDownloadRoute
  '/wireframes/system/email-templates': typeof WireframesSystemEmailTemplatesRoute
  '/wireframes/system/notification-center': typeof WireframesSystemNotificationCenterRoute
  '/wireframes/system/support-tickets': typeof WireframesSystemSupportTicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wireframes/communication-center': typeof WireframesCommunicationCenterRoute
  '/wireframes/landing': typeof WireframesLandingRoute
  '/wireframes/product': typeof WireframesProductRoute
  '/wireframes/profile': typeof WireframesProfileRoute
  '/wireframes/profile-management': typeof WireframesProfileManagementRoute
  '/wireframes/search': typeof WireframesSearchRoute
  '/wireframes/settings': typeof WireframesSettingsRoute
  '/wireframes/accountant/dashboard': typeof WireframesAccountantDashboardRoute
  '/wireframes/accountant/payment-verify': typeof WireframesAccountantPaymentVerifyRoute
  '/wireframes/admin/admin-kyc-approval': typeof WireframesAdminAdminKycApprovalRoute
  '/wireframes/admin/admin-product-moderation': typeof WireframesAdminAdminProductModerationRoute
  '/wireframes/admin/analytics': typeof WireframesAdminAnalyticsRoute
  '/wireframes/admin/contract-management': typeof WireframesAdminContractManagementRoute
  '/wireframes/admin/dashboard': typeof WireframesAdminDashboardRoute
  '/wireframes/admin/financial-reports': typeof WireframesAdminFinancialReportsRoute
  '/wireframes/admin/offer-management': typeof WireframesAdminOfferManagementRoute
  '/wireframes/admin/role-management': typeof WireframesAdminRoleManagementRoute
  '/wireframes/admin/system-monitoring': typeof WireframesAdminSystemMonitoringRoute
  '/wireframes/admin/user-management': typeof WireframesAdminUserManagementRoute
  '/wireframes/authentication/email-verification': typeof WireframesAuthenticationEmailVerificationRoute
  '/wireframes/authentication/forgot-password': typeof WireframesAuthenticationForgotPasswordRoute
  '/wireframes/authentication/kyc': typeof WireframesAuthenticationKycRoute
  '/wireframes/authentication/login': typeof WireframesAuthenticationLoginRoute
  '/wireframes/authentication/reset-password': typeof WireframesAuthenticationResetPasswordRoute
  '/wireframes/authentication/signup': typeof WireframesAuthenticationSignupRoute
  '/wireframes/buyer/contract-management': typeof WireframesBuyerContractManagementRoute
  '/wireframes/buyer/create-offer': typeof WireframesBuyerCreateOfferRoute
  '/wireframes/buyer/dashboard': typeof WireframesBuyerDashboardRoute
  '/wireframes/buyer/library': typeof WireframesBuyerLibraryRoute
  '/wireframes/buyer/offer-review-sign': typeof WireframesBuyerOfferReviewSignRoute
  '/wireframes/buyer/offer-tracking': typeof WireframesBuyerOfferTrackingRoute
  '/wireframes/buyer/payment': typeof WireframesBuyerPaymentRoute
  '/wireframes/contract-manager/create-contract': typeof WireframesContractManagerCreateContractRoute
  '/wireframes/contract-manager/dashboard': typeof WireframesContractManagerDashboardRoute
  '/wireframes/legal/contract-templates': typeof WireframesLegalContractTemplatesRoute
  '/wireframes/legal/dispute-resolution': typeof WireframesLegalDisputeResolutionRoute
  '/wireframes/legal/document-center': typeof WireframesLegalDocumentCenterRoute
  '/wireframes/moderator/dashboard': typeof WireframesModeratorDashboardRoute
  '/wireframes/seller/add-product': typeof WireframesSellerAddProductRoute
  '/wireframes/seller/contract-management': typeof WireframesSellerContractManagementRoute
  '/wireframes/seller/dashboard': typeof WireframesSellerDashboardRoute
  '/wireframes/seller/offer': typeof WireframesSellerOfferRoute
  '/wireframes/seller/offer-analytics': typeof WireframesSellerOfferAnalyticsRoute
  '/wireframes/seller/offer-management': typeof WireframesSellerOfferManagementRoute
  '/wireframes/seller/product-management': typeof WireframesSellerProductManagementRoute
  '/wireframes/system/delivery-download': typeof WireframesSystemDeliveryDownloadRoute
  '/wireframes/system/email-templates': typeof WireframesSystemEmailTemplatesRoute
  '/wireframes/system/notification-center': typeof WireframesSystemNotificationCenterRoute
  '/wireframes/system/support-tickets': typeof WireframesSystemSupportTicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/wireframes/communication-center'
    | '/wireframes/landing'
    | '/wireframes/product'
    | '/wireframes/profile'
    | '/wireframes/profile-management'
    | '/wireframes/search'
    | '/wireframes/settings'
    | '/wireframes/accountant/dashboard'
    | '/wireframes/accountant/payment-verify'
    | '/wireframes/admin/admin-kyc-approval'
    | '/wireframes/admin/admin-product-moderation'
    | '/wireframes/admin/analytics'
    | '/wireframes/admin/contract-management'
    | '/wireframes/admin/dashboard'
    | '/wireframes/admin/financial-reports'
    | '/wireframes/admin/offer-management'
    | '/wireframes/admin/role-management'
    | '/wireframes/admin/system-monitoring'
    | '/wireframes/admin/user-management'
    | '/wireframes/authentication/email-verification'
    | '/wireframes/authentication/forgot-password'
    | '/wireframes/authentication/kyc'
    | '/wireframes/authentication/login'
    | '/wireframes/authentication/reset-password'
    | '/wireframes/authentication/signup'
    | '/wireframes/buyer/contract-management'
    | '/wireframes/buyer/create-offer'
    | '/wireframes/buyer/dashboard'
    | '/wireframes/buyer/library'
    | '/wireframes/buyer/offer-review-sign'
    | '/wireframes/buyer/offer-tracking'
    | '/wireframes/buyer/payment'
    | '/wireframes/contract-manager/create-contract'
    | '/wireframes/contract-manager/dashboard'
    | '/wireframes/legal/contract-templates'
    | '/wireframes/legal/dispute-resolution'
    | '/wireframes/legal/document-center'
    | '/wireframes/moderator/dashboard'
    | '/wireframes/seller/add-product'
    | '/wireframes/seller/contract-management'
    | '/wireframes/seller/dashboard'
    | '/wireframes/seller/offer'
    | '/wireframes/seller/offer-analytics'
    | '/wireframes/seller/offer-management'
    | '/wireframes/seller/product-management'
    | '/wireframes/system/delivery-download'
    | '/wireframes/system/email-templates'
    | '/wireframes/system/notification-center'
    | '/wireframes/system/support-tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/wireframes/communication-center'
    | '/wireframes/landing'
    | '/wireframes/product'
    | '/wireframes/profile'
    | '/wireframes/profile-management'
    | '/wireframes/search'
    | '/wireframes/settings'
    | '/wireframes/accountant/dashboard'
    | '/wireframes/accountant/payment-verify'
    | '/wireframes/admin/admin-kyc-approval'
    | '/wireframes/admin/admin-product-moderation'
    | '/wireframes/admin/analytics'
    | '/wireframes/admin/contract-management'
    | '/wireframes/admin/dashboard'
    | '/wireframes/admin/financial-reports'
    | '/wireframes/admin/offer-management'
    | '/wireframes/admin/role-management'
    | '/wireframes/admin/system-monitoring'
    | '/wireframes/admin/user-management'
    | '/wireframes/authentication/email-verification'
    | '/wireframes/authentication/forgot-password'
    | '/wireframes/authentication/kyc'
    | '/wireframes/authentication/login'
    | '/wireframes/authentication/reset-password'
    | '/wireframes/authentication/signup'
    | '/wireframes/buyer/contract-management'
    | '/wireframes/buyer/create-offer'
    | '/wireframes/buyer/dashboard'
    | '/wireframes/buyer/library'
    | '/wireframes/buyer/offer-review-sign'
    | '/wireframes/buyer/offer-tracking'
    | '/wireframes/buyer/payment'
    | '/wireframes/contract-manager/create-contract'
    | '/wireframes/contract-manager/dashboard'
    | '/wireframes/legal/contract-templates'
    | '/wireframes/legal/dispute-resolution'
    | '/wireframes/legal/document-center'
    | '/wireframes/moderator/dashboard'
    | '/wireframes/seller/add-product'
    | '/wireframes/seller/contract-management'
    | '/wireframes/seller/dashboard'
    | '/wireframes/seller/offer'
    | '/wireframes/seller/offer-analytics'
    | '/wireframes/seller/offer-management'
    | '/wireframes/seller/product-management'
    | '/wireframes/system/delivery-download'
    | '/wireframes/system/email-templates'
    | '/wireframes/system/notification-center'
    | '/wireframes/system/support-tickets'
  id:
    | '__root__'
    | '/'
    | '/wireframes/communication-center'
    | '/wireframes/landing'
    | '/wireframes/product'
    | '/wireframes/profile'
    | '/wireframes/profile-management'
    | '/wireframes/search'
    | '/wireframes/settings'
    | '/wireframes/accountant/dashboard'
    | '/wireframes/accountant/payment-verify'
    | '/wireframes/admin/admin-kyc-approval'
    | '/wireframes/admin/admin-product-moderation'
    | '/wireframes/admin/analytics'
    | '/wireframes/admin/contract-management'
    | '/wireframes/admin/dashboard'
    | '/wireframes/admin/financial-reports'
    | '/wireframes/admin/offer-management'
    | '/wireframes/admin/role-management'
    | '/wireframes/admin/system-monitoring'
    | '/wireframes/admin/user-management'
    | '/wireframes/authentication/email-verification'
    | '/wireframes/authentication/forgot-password'
    | '/wireframes/authentication/kyc'
    | '/wireframes/authentication/login'
    | '/wireframes/authentication/reset-password'
    | '/wireframes/authentication/signup'
    | '/wireframes/buyer/contract-management'
    | '/wireframes/buyer/create-offer'
    | '/wireframes/buyer/dashboard'
    | '/wireframes/buyer/library'
    | '/wireframes/buyer/offer-review-sign'
    | '/wireframes/buyer/offer-tracking'
    | '/wireframes/buyer/payment'
    | '/wireframes/contract-manager/create-contract'
    | '/wireframes/contract-manager/dashboard'
    | '/wireframes/legal/contract-templates'
    | '/wireframes/legal/dispute-resolution'
    | '/wireframes/legal/document-center'
    | '/wireframes/moderator/dashboard'
    | '/wireframes/seller/add-product'
    | '/wireframes/seller/contract-management'
    | '/wireframes/seller/dashboard'
    | '/wireframes/seller/offer'
    | '/wireframes/seller/offer-analytics'
    | '/wireframes/seller/offer-management'
    | '/wireframes/seller/product-management'
    | '/wireframes/system/delivery-download'
    | '/wireframes/system/email-templates'
    | '/wireframes/system/notification-center'
    | '/wireframes/system/support-tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WireframesCommunicationCenterRoute: typeof WireframesCommunicationCenterRoute
  WireframesLandingRoute: typeof WireframesLandingRoute
  WireframesProductRoute: typeof WireframesProductRoute
  WireframesProfileRoute: typeof WireframesProfileRoute
  WireframesProfileManagementRoute: typeof WireframesProfileManagementRoute
  WireframesSearchRoute: typeof WireframesSearchRoute
  WireframesSettingsRoute: typeof WireframesSettingsRoute
  WireframesAccountantDashboardRoute: typeof WireframesAccountantDashboardRoute
  WireframesAccountantPaymentVerifyRoute: typeof WireframesAccountantPaymentVerifyRoute
  WireframesAdminAdminKycApprovalRoute: typeof WireframesAdminAdminKycApprovalRoute
  WireframesAdminAdminProductModerationRoute: typeof WireframesAdminAdminProductModerationRoute
  WireframesAdminAnalyticsRoute: typeof WireframesAdminAnalyticsRoute
  WireframesAdminContractManagementRoute: typeof WireframesAdminContractManagementRoute
  WireframesAdminDashboardRoute: typeof WireframesAdminDashboardRoute
  WireframesAdminFinancialReportsRoute: typeof WireframesAdminFinancialReportsRoute
  WireframesAdminOfferManagementRoute: typeof WireframesAdminOfferManagementRoute
  WireframesAdminRoleManagementRoute: typeof WireframesAdminRoleManagementRoute
  WireframesAdminSystemMonitoringRoute: typeof WireframesAdminSystemMonitoringRoute
  WireframesAdminUserManagementRoute: typeof WireframesAdminUserManagementRoute
  WireframesAuthenticationEmailVerificationRoute: typeof WireframesAuthenticationEmailVerificationRoute
  WireframesAuthenticationForgotPasswordRoute: typeof WireframesAuthenticationForgotPasswordRoute
  WireframesAuthenticationKycRoute: typeof WireframesAuthenticationKycRoute
  WireframesAuthenticationLoginRoute: typeof WireframesAuthenticationLoginRoute
  WireframesAuthenticationResetPasswordRoute: typeof WireframesAuthenticationResetPasswordRoute
  WireframesAuthenticationSignupRoute: typeof WireframesAuthenticationSignupRoute
  WireframesBuyerContractManagementRoute: typeof WireframesBuyerContractManagementRoute
  WireframesBuyerCreateOfferRoute: typeof WireframesBuyerCreateOfferRoute
  WireframesBuyerDashboardRoute: typeof WireframesBuyerDashboardRoute
  WireframesBuyerLibraryRoute: typeof WireframesBuyerLibraryRoute
  WireframesBuyerOfferReviewSignRoute: typeof WireframesBuyerOfferReviewSignRoute
  WireframesBuyerOfferTrackingRoute: typeof WireframesBuyerOfferTrackingRoute
  WireframesBuyerPaymentRoute: typeof WireframesBuyerPaymentRoute
  WireframesContractManagerCreateContractRoute: typeof WireframesContractManagerCreateContractRoute
  WireframesContractManagerDashboardRoute: typeof WireframesContractManagerDashboardRoute
  WireframesLegalContractTemplatesRoute: typeof WireframesLegalContractTemplatesRoute
  WireframesLegalDisputeResolutionRoute: typeof WireframesLegalDisputeResolutionRoute
  WireframesLegalDocumentCenterRoute: typeof WireframesLegalDocumentCenterRoute
  WireframesModeratorDashboardRoute: typeof WireframesModeratorDashboardRoute
  WireframesSellerAddProductRoute: typeof WireframesSellerAddProductRoute
  WireframesSellerContractManagementRoute: typeof WireframesSellerContractManagementRoute
  WireframesSellerDashboardRoute: typeof WireframesSellerDashboardRoute
  WireframesSellerOfferRoute: typeof WireframesSellerOfferRoute
  WireframesSellerOfferAnalyticsRoute: typeof WireframesSellerOfferAnalyticsRoute
  WireframesSellerOfferManagementRoute: typeof WireframesSellerOfferManagementRoute
  WireframesSellerProductManagementRoute: typeof WireframesSellerProductManagementRoute
  WireframesSystemDeliveryDownloadRoute: typeof WireframesSystemDeliveryDownloadRoute
  WireframesSystemEmailTemplatesRoute: typeof WireframesSystemEmailTemplatesRoute
  WireframesSystemNotificationCenterRoute: typeof WireframesSystemNotificationCenterRoute
  WireframesSystemSupportTicketsRoute: typeof WireframesSystemSupportTicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/settings': {
      id: '/wireframes/settings'
      path: '/wireframes/settings'
      fullPath: '/wireframes/settings'
      preLoaderRoute: typeof WireframesSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/search': {
      id: '/wireframes/search'
      path: '/wireframes/search'
      fullPath: '/wireframes/search'
      preLoaderRoute: typeof WireframesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/profile-management': {
      id: '/wireframes/profile-management'
      path: '/wireframes/profile-management'
      fullPath: '/wireframes/profile-management'
      preLoaderRoute: typeof WireframesProfileManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/profile': {
      id: '/wireframes/profile'
      path: '/wireframes/profile'
      fullPath: '/wireframes/profile'
      preLoaderRoute: typeof WireframesProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/product': {
      id: '/wireframes/product'
      path: '/wireframes/product'
      fullPath: '/wireframes/product'
      preLoaderRoute: typeof WireframesProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/landing': {
      id: '/wireframes/landing'
      path: '/wireframes/landing'
      fullPath: '/wireframes/landing'
      preLoaderRoute: typeof WireframesLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/communication-center': {
      id: '/wireframes/communication-center'
      path: '/wireframes/communication-center'
      fullPath: '/wireframes/communication-center'
      preLoaderRoute: typeof WireframesCommunicationCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/system/support-tickets': {
      id: '/wireframes/system/support-tickets'
      path: '/wireframes/system/support-tickets'
      fullPath: '/wireframes/system/support-tickets'
      preLoaderRoute: typeof WireframesSystemSupportTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/system/notification-center': {
      id: '/wireframes/system/notification-center'
      path: '/wireframes/system/notification-center'
      fullPath: '/wireframes/system/notification-center'
      preLoaderRoute: typeof WireframesSystemNotificationCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/system/email-templates': {
      id: '/wireframes/system/email-templates'
      path: '/wireframes/system/email-templates'
      fullPath: '/wireframes/system/email-templates'
      preLoaderRoute: typeof WireframesSystemEmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/system/delivery-download': {
      id: '/wireframes/system/delivery-download'
      path: '/wireframes/system/delivery-download'
      fullPath: '/wireframes/system/delivery-download'
      preLoaderRoute: typeof WireframesSystemDeliveryDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/seller/product-management': {
      id: '/wireframes/seller/product-management'
      path: '/wireframes/seller/product-management'
      fullPath: '/wireframes/seller/product-management'
      preLoaderRoute: typeof WireframesSellerProductManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/seller/offer-management': {
      id: '/wireframes/seller/offer-management'
      path: '/wireframes/seller/offer-management'
      fullPath: '/wireframes/seller/offer-management'
      preLoaderRoute: typeof WireframesSellerOfferManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/seller/offer-analytics': {
      id: '/wireframes/seller/offer-analytics'
      path: '/wireframes/seller/offer-analytics'
      fullPath: '/wireframes/seller/offer-analytics'
      preLoaderRoute: typeof WireframesSellerOfferAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/seller/offer': {
      id: '/wireframes/seller/offer'
      path: '/wireframes/seller/offer'
      fullPath: '/wireframes/seller/offer'
      preLoaderRoute: typeof WireframesSellerOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/seller/dashboard': {
      id: '/wireframes/seller/dashboard'
      path: '/wireframes/seller/dashboard'
      fullPath: '/wireframes/seller/dashboard'
      preLoaderRoute: typeof WireframesSellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/seller/contract-management': {
      id: '/wireframes/seller/contract-management'
      path: '/wireframes/seller/contract-management'
      fullPath: '/wireframes/seller/contract-management'
      preLoaderRoute: typeof WireframesSellerContractManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/seller/add-product': {
      id: '/wireframes/seller/add-product'
      path: '/wireframes/seller/add-product'
      fullPath: '/wireframes/seller/add-product'
      preLoaderRoute: typeof WireframesSellerAddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/moderator/dashboard': {
      id: '/wireframes/moderator/dashboard'
      path: '/wireframes/moderator/dashboard'
      fullPath: '/wireframes/moderator/dashboard'
      preLoaderRoute: typeof WireframesModeratorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/legal/document-center': {
      id: '/wireframes/legal/document-center'
      path: '/wireframes/legal/document-center'
      fullPath: '/wireframes/legal/document-center'
      preLoaderRoute: typeof WireframesLegalDocumentCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/legal/dispute-resolution': {
      id: '/wireframes/legal/dispute-resolution'
      path: '/wireframes/legal/dispute-resolution'
      fullPath: '/wireframes/legal/dispute-resolution'
      preLoaderRoute: typeof WireframesLegalDisputeResolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/legal/contract-templates': {
      id: '/wireframes/legal/contract-templates'
      path: '/wireframes/legal/contract-templates'
      fullPath: '/wireframes/legal/contract-templates'
      preLoaderRoute: typeof WireframesLegalContractTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/contract-manager/dashboard': {
      id: '/wireframes/contract-manager/dashboard'
      path: '/wireframes/contract-manager/dashboard'
      fullPath: '/wireframes/contract-manager/dashboard'
      preLoaderRoute: typeof WireframesContractManagerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/contract-manager/create-contract': {
      id: '/wireframes/contract-manager/create-contract'
      path: '/wireframes/contract-manager/create-contract'
      fullPath: '/wireframes/contract-manager/create-contract'
      preLoaderRoute: typeof WireframesContractManagerCreateContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/buyer/payment': {
      id: '/wireframes/buyer/payment'
      path: '/wireframes/buyer/payment'
      fullPath: '/wireframes/buyer/payment'
      preLoaderRoute: typeof WireframesBuyerPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/buyer/offer-tracking': {
      id: '/wireframes/buyer/offer-tracking'
      path: '/wireframes/buyer/offer-tracking'
      fullPath: '/wireframes/buyer/offer-tracking'
      preLoaderRoute: typeof WireframesBuyerOfferTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/buyer/offer-review-sign': {
      id: '/wireframes/buyer/offer-review-sign'
      path: '/wireframes/buyer/offer-review-sign'
      fullPath: '/wireframes/buyer/offer-review-sign'
      preLoaderRoute: typeof WireframesBuyerOfferReviewSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/buyer/library': {
      id: '/wireframes/buyer/library'
      path: '/wireframes/buyer/library'
      fullPath: '/wireframes/buyer/library'
      preLoaderRoute: typeof WireframesBuyerLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/buyer/dashboard': {
      id: '/wireframes/buyer/dashboard'
      path: '/wireframes/buyer/dashboard'
      fullPath: '/wireframes/buyer/dashboard'
      preLoaderRoute: typeof WireframesBuyerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/buyer/create-offer': {
      id: '/wireframes/buyer/create-offer'
      path: '/wireframes/buyer/create-offer'
      fullPath: '/wireframes/buyer/create-offer'
      preLoaderRoute: typeof WireframesBuyerCreateOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/buyer/contract-management': {
      id: '/wireframes/buyer/contract-management'
      path: '/wireframes/buyer/contract-management'
      fullPath: '/wireframes/buyer/contract-management'
      preLoaderRoute: typeof WireframesBuyerContractManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/authentication/signup': {
      id: '/wireframes/authentication/signup'
      path: '/wireframes/authentication/signup'
      fullPath: '/wireframes/authentication/signup'
      preLoaderRoute: typeof WireframesAuthenticationSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/authentication/reset-password': {
      id: '/wireframes/authentication/reset-password'
      path: '/wireframes/authentication/reset-password'
      fullPath: '/wireframes/authentication/reset-password'
      preLoaderRoute: typeof WireframesAuthenticationResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/authentication/login': {
      id: '/wireframes/authentication/login'
      path: '/wireframes/authentication/login'
      fullPath: '/wireframes/authentication/login'
      preLoaderRoute: typeof WireframesAuthenticationLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/authentication/kyc': {
      id: '/wireframes/authentication/kyc'
      path: '/wireframes/authentication/kyc'
      fullPath: '/wireframes/authentication/kyc'
      preLoaderRoute: typeof WireframesAuthenticationKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/authentication/forgot-password': {
      id: '/wireframes/authentication/forgot-password'
      path: '/wireframes/authentication/forgot-password'
      fullPath: '/wireframes/authentication/forgot-password'
      preLoaderRoute: typeof WireframesAuthenticationForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/authentication/email-verification': {
      id: '/wireframes/authentication/email-verification'
      path: '/wireframes/authentication/email-verification'
      fullPath: '/wireframes/authentication/email-verification'
      preLoaderRoute: typeof WireframesAuthenticationEmailVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/admin/user-management': {
      id: '/wireframes/admin/user-management'
      path: '/wireframes/admin/user-management'
      fullPath: '/wireframes/admin/user-management'
      preLoaderRoute: typeof WireframesAdminUserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/admin/system-monitoring': {
      id: '/wireframes/admin/system-monitoring'
      path: '/wireframes/admin/system-monitoring'
      fullPath: '/wireframes/admin/system-monitoring'
      preLoaderRoute: typeof WireframesAdminSystemMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/admin/role-management': {
      id: '/wireframes/admin/role-management'
      path: '/wireframes/admin/role-management'
      fullPath: '/wireframes/admin/role-management'
      preLoaderRoute: typeof WireframesAdminRoleManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/admin/offer-management': {
      id: '/wireframes/admin/offer-management'
      path: '/wireframes/admin/offer-management'
      fullPath: '/wireframes/admin/offer-management'
      preLoaderRoute: typeof WireframesAdminOfferManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/admin/financial-reports': {
      id: '/wireframes/admin/financial-reports'
      path: '/wireframes/admin/financial-reports'
      fullPath: '/wireframes/admin/financial-reports'
      preLoaderRoute: typeof WireframesAdminFinancialReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/admin/dashboard': {
      id: '/wireframes/admin/dashboard'
      path: '/wireframes/admin/dashboard'
      fullPath: '/wireframes/admin/dashboard'
      preLoaderRoute: typeof WireframesAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/admin/contract-management': {
      id: '/wireframes/admin/contract-management'
      path: '/wireframes/admin/contract-management'
      fullPath: '/wireframes/admin/contract-management'
      preLoaderRoute: typeof WireframesAdminContractManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/admin/analytics': {
      id: '/wireframes/admin/analytics'
      path: '/wireframes/admin/analytics'
      fullPath: '/wireframes/admin/analytics'
      preLoaderRoute: typeof WireframesAdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/admin/admin-product-moderation': {
      id: '/wireframes/admin/admin-product-moderation'
      path: '/wireframes/admin/admin-product-moderation'
      fullPath: '/wireframes/admin/admin-product-moderation'
      preLoaderRoute: typeof WireframesAdminAdminProductModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/admin/admin-kyc-approval': {
      id: '/wireframes/admin/admin-kyc-approval'
      path: '/wireframes/admin/admin-kyc-approval'
      fullPath: '/wireframes/admin/admin-kyc-approval'
      preLoaderRoute: typeof WireframesAdminAdminKycApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/accountant/payment-verify': {
      id: '/wireframes/accountant/payment-verify'
      path: '/wireframes/accountant/payment-verify'
      fullPath: '/wireframes/accountant/payment-verify'
      preLoaderRoute: typeof WireframesAccountantPaymentVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireframes/accountant/dashboard': {
      id: '/wireframes/accountant/dashboard'
      path: '/wireframes/accountant/dashboard'
      fullPath: '/wireframes/accountant/dashboard'
      preLoaderRoute: typeof WireframesAccountantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WireframesCommunicationCenterRoute: WireframesCommunicationCenterRoute,
  WireframesLandingRoute: WireframesLandingRoute,
  WireframesProductRoute: WireframesProductRoute,
  WireframesProfileRoute: WireframesProfileRoute,
  WireframesProfileManagementRoute: WireframesProfileManagementRoute,
  WireframesSearchRoute: WireframesSearchRoute,
  WireframesSettingsRoute: WireframesSettingsRoute,
  WireframesAccountantDashboardRoute: WireframesAccountantDashboardRoute,
  WireframesAccountantPaymentVerifyRoute:
    WireframesAccountantPaymentVerifyRoute,
  WireframesAdminAdminKycApprovalRoute: WireframesAdminAdminKycApprovalRoute,
  WireframesAdminAdminProductModerationRoute:
    WireframesAdminAdminProductModerationRoute,
  WireframesAdminAnalyticsRoute: WireframesAdminAnalyticsRoute,
  WireframesAdminContractManagementRoute:
    WireframesAdminContractManagementRoute,
  WireframesAdminDashboardRoute: WireframesAdminDashboardRoute,
  WireframesAdminFinancialReportsRoute: WireframesAdminFinancialReportsRoute,
  WireframesAdminOfferManagementRoute: WireframesAdminOfferManagementRoute,
  WireframesAdminRoleManagementRoute: WireframesAdminRoleManagementRoute,
  WireframesAdminSystemMonitoringRoute: WireframesAdminSystemMonitoringRoute,
  WireframesAdminUserManagementRoute: WireframesAdminUserManagementRoute,
  WireframesAuthenticationEmailVerificationRoute:
    WireframesAuthenticationEmailVerificationRoute,
  WireframesAuthenticationForgotPasswordRoute:
    WireframesAuthenticationForgotPasswordRoute,
  WireframesAuthenticationKycRoute: WireframesAuthenticationKycRoute,
  WireframesAuthenticationLoginRoute: WireframesAuthenticationLoginRoute,
  WireframesAuthenticationResetPasswordRoute:
    WireframesAuthenticationResetPasswordRoute,
  WireframesAuthenticationSignupRoute: WireframesAuthenticationSignupRoute,
  WireframesBuyerContractManagementRoute:
    WireframesBuyerContractManagementRoute,
  WireframesBuyerCreateOfferRoute: WireframesBuyerCreateOfferRoute,
  WireframesBuyerDashboardRoute: WireframesBuyerDashboardRoute,
  WireframesBuyerLibraryRoute: WireframesBuyerLibraryRoute,
  WireframesBuyerOfferReviewSignRoute: WireframesBuyerOfferReviewSignRoute,
  WireframesBuyerOfferTrackingRoute: WireframesBuyerOfferTrackingRoute,
  WireframesBuyerPaymentRoute: WireframesBuyerPaymentRoute,
  WireframesContractManagerCreateContractRoute:
    WireframesContractManagerCreateContractRoute,
  WireframesContractManagerDashboardRoute:
    WireframesContractManagerDashboardRoute,
  WireframesLegalContractTemplatesRoute: WireframesLegalContractTemplatesRoute,
  WireframesLegalDisputeResolutionRoute: WireframesLegalDisputeResolutionRoute,
  WireframesLegalDocumentCenterRoute: WireframesLegalDocumentCenterRoute,
  WireframesModeratorDashboardRoute: WireframesModeratorDashboardRoute,
  WireframesSellerAddProductRoute: WireframesSellerAddProductRoute,
  WireframesSellerContractManagementRoute:
    WireframesSellerContractManagementRoute,
  WireframesSellerDashboardRoute: WireframesSellerDashboardRoute,
  WireframesSellerOfferRoute: WireframesSellerOfferRoute,
  WireframesSellerOfferAnalyticsRoute: WireframesSellerOfferAnalyticsRoute,
  WireframesSellerOfferManagementRoute: WireframesSellerOfferManagementRoute,
  WireframesSellerProductManagementRoute:
    WireframesSellerProductManagementRoute,
  WireframesSystemDeliveryDownloadRoute: WireframesSystemDeliveryDownloadRoute,
  WireframesSystemEmailTemplatesRoute: WireframesSystemEmailTemplatesRoute,
  WireframesSystemNotificationCenterRoute:
    WireframesSystemNotificationCenterRoute,
  WireframesSystemSupportTicketsRoute: WireframesSystemSupportTicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
